name: Publish to NPM

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check package.json version
        id: check
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            VERSION_CHANGED=$(git diff HEAD~1..HEAD -- 'package.json' | grep '"version":')
            if [ -n "$VERSION_CHANGED" ]; then
              echo "::set-output name=changed::true"
            fi
          fi
        shell: bash
        if: github.event_name == 'push'

      - name: Setup Node
        if: (steps.check.outputs.changed == 'true' && github.event_name == 'push') || github.event_name == 'release'
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package on NPM 📦
        if: (steps.check.outputs.changed == 'true' && github.event_name == 'push') || github.event_name == 'release'
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
